apiVersion: v1
kind: ConfigMap
metadata:
  name: notifications-api-config
data:
  ASPNETCORE_ENVIRONMENT: "Development"
  RabbitMq__Host: "rabbitmq"
  RabbitMq__Username: "guest"
---
apiVersion: v1
kind: Secret
metadata:
  name: notifications-api-secret
type: Opaque
stringData:
  RabbitMq__Password: "guest"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: notifications-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: notifications-api
  template:
    metadata:
      labels:
        app: notifications-api
        admission.datadoghq.com/enabled: "true"
      annotations:
        admission.datadoghq.com/dotnet-lib.version: "3"
    spec:
      containers:
        - name: notifications-api
          image: gu1m4ss1/trezzecloud-notifications-api:latest
          ports:
            - containerPort: 8080
          envFrom:
            - configMapRef:
                name: notifications-api-config
            - secretRef:
                name: notifications-api-secret
---
apiVersion: v1
kind: Service
metadata:
  name: notifications-api
spec:
  type: ClusterIP
  selector:
    app: notifications-api
  ports:
    - port: 80
      targetPort: 8080