apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: apis-from-kong
spec:
  podSelector:
    matchExpressions:
      - key: app
        operator: In
        values: [users-api, catalog-api]
  policyTypes: [Ingress]
  ingress:
    - from:
        - podSelector:
            matchLabels:
              app: kong
      ports:
        - protocol: TCP
          port: 8080
