_format_version: "3.0"
consumers:
  - username: trezzecloud-app
    jwt_secrets:
      - key: TrezzeCloud
        algorithm: HS256
        secret: SUPER_SECRET_KEY_123456789_SUPER_SECRET_KEY
services:
  - name: users-api
    url: http://users-api:80
    routes:
      - name: users-public-route
        paths:
          - /api/users/login
          - /api/users/register
        strip_path: false
      - name: users-protected-route
        paths:
          - /api/users
        strip_path: false
        plugins:
          - name: jwt
            config:
              claims_to_verify:
                - exp
  - name: catalog-api
    url: http://catalog-api:80
    routes:
      - name: catalog-route
        paths:
          - /api/games
        strip_path: false