datadog:
  apiKeyExistingSecret: datadog-secret
  site: datadoghq.com
  clusterName: trezzecloud-local

  logs:
    enabled: true
    containerCollectAll: true

  apm:
    instrumentation:
      enabled: true
      libVersions:
        dotnet: "3"