apiVersion: v1
kind: ConfigMap
metadata:
  name: catalog-api-config
data:
  MongoDb__ConnectionString: mongodb://mongodb:27017
  MongoDb__DatabaseName: TrezzeCloudCatalog
  Redis__ConnectionString: redis:6379
  ASPNETCORE_ENVIRONMENT: "Development"
  RabbitMq__Host: "rabbitmq"
  RabbitMq__Username: "guest"
---
apiVersion: v1
kind: Secret
metadata:
  name: catalog-api-secret
type: Opaque
stringData:
  ConnectionStrings__CatalogDatabase: "Server=sqlserver;Database=TrezzeCloudCatalog;User Id=sa;Password=Your_password123;TrustServerCertificate=True"
  RabbitMq__Password: "guest"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: catalog-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: catalog-api
  template:
    metadata:
      labels:
        app: catalog-api
        admission.datadoghq.com/enabled: "true"
      annotations:
        admission.datadoghq.com/dotnet-lib.version: "3"
    spec:
      containers:
        - name: catalog-api
          image: gu1m4ss1/trezzecloud-catalog-api:latest
          ports:
            - containerPort: 8080
          envFrom:
            - configMapRef:
                name: catalog-api-config
            - secretRef:
                name: catalog-api-secret
            - secretRef:
                name: jwt-secret
---
apiVersion: v1
kind: Service
metadata:
  name: catalog-api
spec:
  type: ClusterIP
  selector:
    app: catalog-api
  ports:
    - port: 8080
      targetPort: 8080
