apiVersion: v1
kind: ConfigMap
metadata:
  name: catalog-api-config
data:
  ASPNETCORE_ENVIRONMENT: "Development"
  RabbitMq__Host: "rabbitmq"
  RabbitMq__Username: "guest"
  Jwt__Issuer: "TrezzeCloud"
  Jwt__Audience: "TrezzeCloud"
---
apiVersion: v1
kind: Secret
metadata:
  name: catalog-api-secret
type: Opaque
stringData:
  ConnectionStrings__CatalogDatabase: "Server=sqlserver;Database=TrezzeCloudCatalog;User Id=sa;Password=Your_password123;TrustServerCertificate=True"
  RabbitMq__Password: "guest"
  Jwt__SecretKey: "SUPER_SECRET_KEY_123456789_SUPER_SECRET_KEY"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: catalog-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: catalog-api
  template:
    metadata:
      labels:
        app: catalog-api
        admission.datadoghq.com/enabled: "true"
      annotations:
        admission.datadoghq.com/dotnet-lib.version: "3"
    spec:
      containers:
        - name: catalog-api
          image: gu1m4ss1/trezzecloud-catalog-api:latest
          ports:
            - containerPort: 8080
          envFrom:
            - configMapRef:
                name: catalog-api-config
            - secretRef:
                name: catalog-api-secret
---
apiVersion: v1
kind: Service
metadata:
  name: catalog-api
spec:
  type: NodePort
  selector:
    app: catalog-api
  ports:
    - port: 80
      targetPort: 8080
      nodePort: 30082