apiVersion: v1
kind: ConfigMap
metadata:
  name: users-api-config
data:
  ASPNETCORE_ENVIRONMENT: "Development"
  RabbitMq__Host: "rabbitmq"
  RabbitMq__Username: "guest"
  AdminUser__Name: "TrezzeCloud Admin"
  AdminUser__Email: "admin@trezzecloud.com"
---
apiVersion: v1
kind: Secret
metadata:
  name: users-api-secret
type: Opaque
stringData:
  ConnectionStrings__UsersDatabase: "Server=sqlserver;Database=TrezzeCloudUsers;User Id=sa;Password=Your_password123;TrustServerCertificate=True"
  RabbitMq__Password: "guest"
  AdminUser__Password: "Admin@123"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: users-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: users-api
  template:
    metadata:
      labels:
        app: users-api
    spec:
      containers:
        - name: users-api
          image: gu1m4ss1/trezzecloud-users-api:latest
          ports:
            - containerPort: 8080
          envFrom:
            - configMapRef:
                name: users-api-config
            - secretRef:
                name: users-api-secret
            - secretRef:
                name: jwt-secret
---
apiVersion: v1
kind: Service
metadata:
  name: users-api
spec:
  type: ClusterIP
  selector:
    app: users-api
  ports:
    - port: 8080
      targetPort: 8080
